version: '3.8'

services:
  backend:
    container_name: back_container
    build:
      context: back
    environment:
      - JWT_KEY=${JWT_SECRET}
      - MONGO_URL=${MONGO_URL}
      - MONGO_DB=${MONGO_DB}
    ports:
      - 8080:8080
    restart: always
    env_file:
       - .env
