name: Deploy Backend

on:
  push:
    branches:
      - back-release-*
  pull_request:
    branches:
      - back-release-*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: Build with Maven
      run: mvn -B clean package -DskipTests --file back/pom.xml

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and tag Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./back
        push: true
        tags: |
          ebloemer/diagnostic-backend:${{ github.sha }}

    - name: Deploy to DigitalOcean Droplet
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USER }}
        password: ${{ secrets.DROPLET_PASSWORD }}
        script: |
          /home/diagnostic/cicd.sh ${{ github.sha }}
