name: Deploy Frontend

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'front/**'
#   pull_request:
#     branches:
#       - main
#     paths:
#       - 'front/**'  
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Deploy to DigitalOcean Droplet
#       uses: appleboy/ssh-action@v0.1.5
#       with:
#         host: ${{ secrets.DROPLET_HOST }}
#         username: ${{ secrets.DROPLET_USER }}
#         password: ${{ secrets.DROPLET_PASSWORD }}
#         script: |
#           /home/diagnostic/cicd-front.sh

on:
  push:
    branches:
      - main
    paths:
      - 'front/**'
  pull_request:
    branches:
      - main
    paths:
      - 'front/**'  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: '18'
   
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
    - name: Build and tag Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./front
        push: true
        tags: |
          ebloemer/diagnostic-frontend:${{ github.sha }}

    - name: Deploy to DigitalOcean Droplet
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USER }}
        password: ${{ secrets.DROPLET_PASSWORD }}
        script: |
          /home/cicd/cicd-front.sh ${{ github.sha }}
